services:
  - type: web
    name: keycloak
    env: docker
    plan: starter
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    ports:
      - port: 8080
        protocol: http
